[[libwinit]]
arch = "aarch64"
git-tree-sha1 = "e419582b4ed6aa4a38467b4f4ed44549b51352d4"
libc = "glibc"
os = "linux"

    [[libwinit.download]]
    sha256 = "a9d0266fa473e2217dcbbd0d5bb325e9a46c31d8559a4092b618213f15f8ac78"
    url = "https://github.com/JuliaBinaryWrappers/libwinit_jll.jl/releases/download/libwinit-v0.32.0+0/libwinit.v0.32.0.aarch64-linux-gnu.tar.gz"
[[libwinit]]
arch = "powerpc64le"
git-tree-sha1 = "33af1bd306b277e3e88c3d54fbafe0e90ae1b0d5"
libc = "glibc"
os = "linux"

    [[libwinit.download]]
    sha256 = "f8b4a140e3f1a372abf2cbd57d8de60f56602ccb5ee52b619f4782951bdae8da"
    url = "https://github.com/JuliaBinaryWrappers/libwinit_jll.jl/releases/download/libwinit-v0.32.0+0/libwinit.v0.32.0.powerpc64le-linux-gnu.tar.gz"
[[libwinit]]
arch = "x86_64"
git-tree-sha1 = "df907cb3f5d1cd4de8806ad22eb4c534c8465711"
libc = "glibc"
os = "linux"

    [[libwinit.download]]
    sha256 = "09551226885d66af475e2eac7e726aff63b29fe4aac12efedee273b11b41a7cd"
    url = "https://github.com/JuliaBinaryWrappers/libwinit_jll.jl/releases/download/libwinit-v0.32.0+0/libwinit.v0.32.0.x86_64-linux-gnu.tar.gz"
[[libwinit]]
arch = "x86_64"
git-tree-sha1 = "67aa630165570d27e6863c407af6807e01d531ea"
os = "windows"

    [[libwinit.download]]
    sha256 = "bb02e662b124a7aa5487d156ee87e79a1a497480a177b72aa72dc34d2d5da49a"
    url = "https://github.com/JuliaBinaryWrappers/libwinit_jll.jl/releases/download/libwinit-v0.32.0+0/libwinit.v0.32.0.x86_64-w64-mingw32.tar.gz"
