# Autogenerated wrapper script for libwinit_jll for aarch64-linux-gnu
export libWinit, winit_h

using libboxer_jll
JLLWrappers.@generate_wrapper_header("libwinit")
JLLWrappers.@declare_library_product(libWinit, "libWinit.so")
JLLWrappers.@declare_file_product(winit_h)
function __init__()
    JLLWrappers.@generate_init_header(libboxer_jll)
    JLLWrappers.@init_library_product(
        libWinit,
        "lib/libWinit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        winit_h,
        "include/winit.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
