# Autogenerated wrapper script for libwinit_jll for x86_64-w64-mingw32
export libWinit, winit_h

using libboxer_jll
JLLWrappers.@generate_wrapper_header("libwinit")
JLLWrappers.@declare_library_product(libWinit, "libWinit.dll")
JLLWrappers.@declare_file_product(winit_h)
function __init__()
    JLLWrappers.@generate_init_header(libboxer_jll)
    JLLWrappers.@init_library_product(
        libWinit,
        "bin\\libWinit.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        winit_h,
        "include\\winit.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
